### ISSUE TITLE
Its Error ThaumcraftNoResearch?

### ISSUE THREAD

**Issue by kellixon** [rinart73/ThaumcraftNoResearch#1]
MC 1.12.2. Log from the computer from the local network, spam 200.000 lines. On the main (server) there are no errors. Full log - https://gist.github.com/kellixon/4b67386cff18ef3e735e367176600229 (spam from line 106681; the part of a log deleted, as the file size was under 60 megabytes)
`[16:56:02] [Client thread/ERROR] [FML]: SimpleChannelHandlerWrapper exception
java.lang.NullPointerException: null
	at net.minecraftforge.fml.common.network.FMLOutboundHandler$OutboundTarget$7.selectNetworks(FMLOutboundHandler.java:224) ~[FMLOutboundHandler$OutboundTarget$7.class:?]
	at net.minecraftforge.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:378) ~[FMLOutboundHandler.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111) ~[MessageToMessageEncoder.class:4.1.9.Final]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[DefaultChannelPipeline.class:4.1.9.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[AbstractChannel.class:4.1.9.Final]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAllAround(SimpleNetworkWrapper.java:264) [SimpleNetworkWrapper.class:?]
	at thaumcraft.common.tiles.TileThaumcraft.sendMessageToClient(TileThaumcraft.java:33) [TileThaumcraft.class:?]
	at thaumcraft.common.tiles.TileThaumcraftInventory.syncSlots(TileThaumcraftInventory.java:134) [TileThaumcraftInventory.class:?]
	at thaumcraft.common.tiles.TileThaumcraftInventory.syncTile(TileThaumcraftInventory.java:141) [TileThaumcraftInventory.class:?]
	at thaumcraft.common.tiles.crafting.TileResearchTable.onDataPacket(TileResearchTable.java:182) [TileResearchTable.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.handleUpdateTileEntity(NetHandlerPlayClient.java:1231) [brz.class:?]
	at net.minecraft.network.play.server.SPacketUpdateTileEntity.processPacket(SourceFile:54) [ih.class:?]
	at net.minecraft.network.play.server.SPacketUpdateTileEntity.processPacket(SourceFile:11) [ih.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:20) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_192]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_192]
	at net.minecraft.util.Util.runTask(Util.java:529) [h.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1088) [bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:3942) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_192]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_192]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_192]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]`

**Comment by rinart73** [comment]
From what I can see, it's a Thaumcraft bug related to the Research Table. My mod doesn't fix Research Table, it just allows to **not use it**. Because you already have a lot of research points you don't need to use Research Table.

**Comment by kellixon** [comment]
THANK YOU VERY MUCH! Now I see!
